# this code was generated by chatGPT with the following prompt:
"give me a python code script for the bitcraze crazyflie 2.1 that uses PWM controls to move forward"

import logging
import sys
import time

import cflib.crtp
from cflib.crazyflie import Crazyflie
from cflib.crazyflie.syncCrazyflie import SyncCrazyflie
from cflib.positioning.motion_commander import MotionCommander
from cflib.utils.multiranger import Multiranger

URI = 'radio://0/80/2M'

if len(sys.argv) > 1:
    URI = sys.argv[1]

# Only output errors from the logging framework
logging.basicConfig(level=logging.ERROR)


def is_close(range):
    MIN_DISTANCE = 0.2  # m

    if range is None:
        return False
    else:
        return range < MIN_DISTANCE


if __name__ == '__main__':
    # Initialize the low-level drivers (don't list the debug drivers)
    cflib.crtp.init_drivers(enable_debug_driver=False)

    cf = Crazyflie(rw_cache='./cache')
    with SyncCrazyflie(URI, cf=cf) as scf:

# PWM range: 0–65535 (be conservative!)
        BASE_PWM = 20000
        FORWARD_BOOST = 3000

def move_forward_pwm(cf, duration=2.0):
    """
    Motor layout:
      M1: front left
      M2: front right
      M3: rear right
      M4: rear left
    """

    # Take off (simple hover-ish)
    cf.commander.send_motor_power_set(
        BASE_PWM,
        BASE_PWM,
        BASE_PWM,
        BASE_PWM
    )
    time.sleep(1.0)

    # Move forward (boost rear motors)
    cf.commander.send_motor_power_set(
        BASE_PWM,
        BASE_PWM,
        BASE_PWM + FORWARD_BOOST,
        BASE_PWM + FORWARD_BOOST
    )
    time.sleep(duration)

    # Stop motors
    cf.commander.send_motor_power_set(0, 0, 0, 0)

def main():
    cflib.crtp.init_drivers()
    cf = Crazyflie(rw_cache='./cache')

    with SyncCrazyflie(URI, cf=cf):
        time.sleep(1)
        move_forward_pwm(cf)

if __name__ == '__main__':
    main()