# this code was generated by chatGPT with the following prompt:
"give me a python code script for the bitcraze crazyflie 2.1 that prints out current PWM values while still transmitting flight commands to the crazyflie"
import time
import cflib.crtp
from cflib.crazyflie import Crazyflie
from cflib.crazyflie.syncCrazyflie import SyncCrazyflie
from cflib.crazyflie.log import LogConfig

URI = 'radio://0/80/2M/E7E7E7E7E7'

THRUST = 35000  # Adjust carefully

def pwm_log_callback(timestamp, data, logconf):
    m1 = data['motor.m1']
    m2 = data['motor.m2']
    m3 = data['motor.m3']
    m4 = data['motor.m4']

    print(f"PWM | M1:{m1:5d} M2:{m2:5d} M3:{m3:5d} M4:{m4:5d}")

def main():
    cflib.crtp.init_drivers()
    cf = Crazyflie(rw_cache='./cache')

    with SyncCrazyflie(URI, cf=cf):
        time.sleep(1.0)

        # Setup logging
        logconf = LogConfig(name='MotorPWM', period_in_ms=100)
        logconf.add_variable('motor.m1', 'uint16_t')
        logconf.add_variable('motor.m2', 'uint16_t')
        logconf.add_variable('motor.m3', 'uint16_t')
        logconf.add_variable('motor.m4', 'uint16_t')

        cf.log.add_config(logconf)
        logconf.data_received_cb.add_callback(pwm_log_callback)
        logconf.start()

        print("Sending flight commands and logging PWM...")

        try:
            while True:
                # Send stabilizing setpoint (safe, recommended)
                cf.commander.send_setpoint(
                    roll=0.0,
                    pitch=0.0,
                    yawrate=0.0,
                    thrust=THRUST
                )
                time.sleep(0.1)

        except KeyboardInterrupt:
            print("\nStopping motors...")

        finally:
            logconf.stop()
            cf.commander.send_stop_setpoint()

if __name__ == '__main__':
    main()