## Example PWM Code for crazyflie generated by Gemini AI

import logging
import sys
import time

import cflib.crtp
from cflib.crazyflie import Crazyflie
from cflib.crazyflie.syncCrazyflie import SyncCrazyflie
from cflib.positioning.motion_commander import MotionCommander
from cflib.utils.multiranger import Multiranger

URI = 'radio://0/80/2M'

if len(sys.argv) > 1:
    URI = sys.argv[1]

# Only output errors from the logging framework
logging.basicConfig(level=logging.ERROR)


def is_close(range):
    MIN_DISTANCE = 0.2  # m

    if range is None:
        return False
    else:
        return range < MIN_DISTANCE


if __name__ == '__main__':
    # Initialize the low-level drivers (don't list the debug drivers)
    cflib.crtp.init_drivers(enable_debug_driver=False)

    cf = Crazyflie(rw_cache='./cache')
    with SyncCrazyflie(URI, cf=cf) as scf:
        # Arm the Crazyflie
        scf.cf.platform.send_arming_request(True)
        time.sleep(1.0)

        with MotionCommander(scf) as mc:
            # Set motorPowerSet.enable to 1 to unlock startup protection and enable manual PWM control
            cf.param.set_value('motorPowerSet.enable', '1')
            # Set system.forceArm to 1 to force arming, bypassing some safety checks
            # cf.param.set_value('system.forceArm', '1')

            # Set M1 motor to a specific PWM value (e.g., 30000 out of 65535)
            for x in range(0,3):
                pwm_value = x*10000
                print(f"Setting M1 PWM to {pwm_value}")
                cf.param.set_value('motorPowerSet.m2', str(pwm_value))
                time.sleep(0.1)

            # Keep the script running for a few seconds to observe motor spin
            time.sleep(5)

            # Stop the motor by setting the PWM to 0
            cf.param.set_value('motorPowerSet.m1', '0')
            cf.param.set_value('motorPowerSet.enable', '0') # Disable manual control
