## Example PWM Code for crazyflie generated by Gemini AI

import time
import cflib.crtp
from cflib.crazyflie.syncCrazyflie import SyncCrazyFlie

# URI to the Crazyflie to connect to
URI = 'radio://0/80/2M/E7E7E7E7E7'

# Initialize the Crazyflie drivers
cflib.crtp.init_drivers(enable_usb_drivers=False)

with SyncCrazyFlie(URI) as scf:
    cf = scf.cf

    # Set motorPowerSet.enable to 1 to unlock startup protection and enable manual PWM control
    cf.param.set_value('motorPowerSet.enable', '1')
    # Set system.forceArm to 1 to force arming, bypassing some safety checks
    cf.param.set_value('system.forceArm', '1')

    # Set M1 motor to a specific PWM value (e.g., 30000 out of 65535)
    pwm_value = 30000
    print(f"Setting M1 PWM to {pwm_value}")
    cf.param.set_value('motorPowerSet.m1', str(pwm_value))

    # Keep the script running for a few seconds to observe motor spin
    time.sleep(5)

    # Stop the motor by setting the PWM to 0
    cf.param.set_value('motorPowerSet.m1', '0')
    cf.param.set_value('motorPowerSet.enable', '0') # Disable manual control
